package com.myapp.struts;
// Generated 10 Jul, 2016 7:49:39 AM by Hibernate Tools 3.2.1.GA



/**
 * Compliance generated by hbm2java
 */
public class Compliance extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private String compliancedate;
     private String remarks;

    public Compliance() {
    }

	
    public Compliance(String compliancedate) {
        this.compliancedate = compliancedate;
    }
    public Compliance(String compliancedate, String remarks) {
       this.compliancedate = compliancedate;
       this.remarks = remarks;
    }
   
    public String getCompliancedate() {
        return this.compliancedate;
    }
    
    public void setCompliancedate(String compliancedate) {
        this.compliancedate = compliancedate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


