package com.myapp.struts;
// Generated 10 Jul, 2016 7:49:39 AM by Hibernate Tools 3.2.1.GA



/**
 * Maintenance generated by hbm2java
 */
public class Maintenance extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String equipment;
     private String area;
     private String frequency;
     private String maintenancedate;
     private String inspected;

    public Maintenance() {
    }

	
    public Maintenance(String equipment) {
        this.equipment = equipment;
    }
    public Maintenance(String equipment, String area, String frequency, String maintenancedate, String inspected) {
       this.equipment = equipment;
       this.area = area;
       this.frequency = frequency;
       this.maintenancedate = maintenancedate;
       this.inspected = inspected;
    }
   
    public String getEquipment() {
        return this.equipment;
    }
    
    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    public String getMaintenancedate() {
        return this.maintenancedate;
    }
    
    public void setMaintenancedate(String maintenancedate) {
        this.maintenancedate = maintenancedate;
    }
    public String getInspected() {
        return this.inspected;
    }
    
    public void setInspected(String inspected) {
        this.inspected = inspected;
    }




}


